%YAML:1.0
---
type: IMU
name: imu0
Gyr:
   unit: " rad/s"
   avg-axis:
      gyr_n: 1.0705850131705037e-03
      gyr_w: 3.7608714011754706e-05
   x-axis:
      gyr_n: 1.1684126217975099e-03
      gyr_w: 3.5799650463172088e-05
   y-axis:
      gyr_n: 1.0768409608233685e-03
      gyr_w: 3.9097015740268039e-05
   z-axis:
      gyr_n: 9.6650145689063224e-04
      gyr_w: 3.7929475831823991e-05
Acc:
   unit: " m/s^2"
   avg-axis:
      acc_n: 1.1716650459018008e-02
      acc_w: 4.3514172629237851e-04
   x-axis:
      acc_n: 9.0882612011539358e-03
      acc_w: 2.9192914865804742e-04
   y-axis:
      acc_n: 8.5539004779091737e-03
      acc_w: 2.2836503817001751e-04
   z-axis:
      acc_n: 1.7507789697990921e-02
      acc_w: 7.8513099204907070e-04
